server:
  port: 9000

# activate microservice routing
spring:
  application:
    name: CAMPUS-API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: STUDENT-SERVICE
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/students/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: STUDENT-SERVICE
#                fallbackuri: forward:/studentServiceFallBack
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: DEPARTMENT-SERVICE
#                fallbackuri: forward:/departmentServiceFallBack

# after not responding within 4-sec (student-service or department-service) fallback API  will get triggered
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

# enable hystrix stream in hystrix dashboard
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream




# enable eureka client api gateway
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka
  instance:
    hostname: localhost
